### ISSUE TITLE
Requires git but doesn't install it

### ISSUE THREAD

**Issue by scheffield** [erasme/ansible-rbenv#3]
Hi,

the role requires the git executable to be present but doesn't install it. This leads to the following error:

```
failed: [default] => {"failed": true}
msg: Failed to find required executable git
```

**Comment by leucos** [comment]
Indeed. Thanks for spotting this @scheffield . Want to send a PR or me to fix it ?

**Comment by scheffield** [comment]
Hi, I'll send you a PR the next days.
